Update helmlint.yaml

diff --git a/.github/workflows/helmlint.yaml b/.github/workflows/helmlint.yaml
--- a/.github/workflows/helmlint.yaml
+++ b/.github/workflows/helmlint.yaml
@@ -25,3 +25,8 @@ jobs:
             echo "The chart didn't pass the lint check!"
             exit 1
           fi
+          helm install microservice-dry-run .  --dry-run
+          if [ $? != 0 ]; then
+            echo "The chart couldn't be rendered, check your templates!"
+            exit 1
+          fi
